---
title: "EOL data" 
author: "Jean-Pierre Gattuso"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  rmarkdown::html_document:
    theme: paper
    number_sections: false
theme: cerulean
fig_width: 12 
fig_height: 8     
---

<style type="text/css">

body{ /* Normal  */
      font-size: 16px;
  }
td {  /* Table  */
  font-size: 14px;
}
h1.title {
  font-size: 38px;
  color: DarkRed;
}
h1 { /* Header 1 */
  font-size: 28px;
  color: DarkBlue;
}
h2 { /* Header 2 */
    font-size: 22px;
  color: DarkBlue;
}
h3 { /* Header 3 */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>

```{r set-up, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
Sys.setlocale("LC_ALL", "en_US.UTF-8")
Sys.setenv(TZ='UTC') # on utilise UTC
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("dygraphs")
library("xts")
library("googledrive")

#define who is the user and define path
if (Sys.getenv("LOGNAME") == "gattuso") path = "../../pCloud\ Sync/Documents/experiments/exp153_carbonates_point_B/"
if (Sys.getenv("LOGNAME") == "samir") path = "../../pCloud Sync/exp153_carbonates_point_B/"
```

```{r read and clean data, echo=FALSE, warning=FALSE, message=FALSE}
url <- "Temperature_EOL/EOL.csv"
drive_download(url, type = "csv", path="data/EOL.CSV")
d <- readr::read_csv(file = "data/EOL.csv", col_names = TRUE) %>% 
  unique() %>% 
  dplyr::mutate(d, date_time = str_c(Date, " ", Heure) %>%
                  parse_datetime(format="%Y%m%d %H%M%S"))

dt <- seq(from=as.POSIXct("2013-09-16 00:00:00", tz="UTC"),
     to=as.POSIXct("2023-01-01 00:00:00", tz="UTC"),
     by="hour")
EOL_xts <- dplyr::select(d, date_time, T)
EOL_xts <- xts::as.xts(EOL_xts, order.by = dt)
dygraph(EOL_xts,
        #group = "awipev",
        main = "Temperature at EOL station, Villefranche-sur-mer",
        ylab = "Temperature (°C)") %>%
  dySeries(
    "T",
    #label = "Raw durafet pH",
    color = "blue",
    strokeWidth = 0,
    pointSize = 2
  )
ggplot(d) + geom_point((aes(x=date_time, y=T)))
saveRDS(d, file = "data/eol_data.rds")
```

